
services:
  web:
    build: .
    ports: ["8080:8080"]
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - OpcUa__Endpoint=opc.tcp://opcua-refserver:50000
      - Seed__Enabled=true
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      postgres:
        condition: service_healthy
      opcua-refserver:
        condition: service_started
      jaeger:
        condition: service_started

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: PlcLab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Your_password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  opcua-refserver:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    ports:
      - "4840:50000"
    restart: unless-stopped
    command: ["--pn=50000", "--unsecuretransport", "--aa"] 
    #--pn=50000     Port number for the OPC UA server
    #--unsecuretransport - Enables None/None security endpoint
    #--aa - Auto-accept all client certificates

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  pgdata:
